"""Initial migration

Revision ID: a45dd1b8783f
Revises: 
Create Date: 2024-09-12 01:45:51.637674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45dd1b8783f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"),
                              autoincrement=True, nullable=False),
                    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='users_pkey'),
                    sa.UniqueConstraint('email', name='users_email_key'),
                    sa.UniqueConstraint('username', name='users_username_key'),
                    postgresql_ignore_search_path=False
                    )
    op.create_table('tasks',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'New'::character varying"),
                              autoincrement=False, nullable=False),
                    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='tasks_user_id_fkey', ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
                    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('tasks')
    op.drop_table('users')
    # ### end Alembic commands ###
